<?php

namespace Database\Seeders;

use App\Models\AdjudicationSection;
use Illuminate\Database\Seeder;

class AdjudicationSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        AdjudicationSection::factory()->create([
            'id' => 1,
            'adjudication_id' => 1,
            'adjudication_section_name' => 'Aamodt',
            'prefix' => 'AAM',
            'adjudication_section_type_id' => 2,
            'boundary_name' => 'Pojoaque River Basin',
            'adjudication_section_status_id' => 4,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 2,
            'adjudication_id' => 1,
            'adjudication_section_name' => 'NPT PM Wells',
            'prefix' => 'PM',
            'adjudication_section_type_id' => 2,
            'boundary_name' => null,
            'adjudication_section_status_id' => 4,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 3,
            'adjudication_id' => 2,
            'adjudication_section_name' => 'Animas',
            'prefix' => 'AUB',
            'adjudication_section_type_id' => 7,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 4,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'CUB - Carlsbad Underground Section',
            'prefix' => 'PCUB',
            'adjudication_section_type_id' => 7,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 5,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Canjilon Creek, Section 3',
            'prefix' => 'CHCJ',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 6,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Canones',
            'prefix' => 'CHCP',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 7,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Canones Creek, Section 7',
            'prefix' => 'CHCC',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 8,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Jicarilla',
            'prefix' => 'CHJA',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 9,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Village of Chama, Section 7',
            'prefix' => 'CHCV',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 10,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Mainstream',
            'prefix' => 'CHMS',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 11,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - El Rito',
            'prefix' => 'CHER',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 12,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Ojo Caliente',
            'prefix' => 'CHOC',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 13,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama -Rio Brazos, Section 7',
            'prefix' => 'CHRB',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 14,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Rio Cebolla, Section 3',
            'prefix' => 'CHCB',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 15,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Rio Cebolla Ponds',
            'prefix' => 'CHCBP',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 16,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Rio del Oso & Rio Vallecito , Section 1',
            'prefix' => 'CHRO',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 17,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Rio Gallina, Section 5',
            'prefix' => 'CHGA',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 18,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Rio Gallina Fed',
            'prefix' => 'CHGAF',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 19,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Rio Nutrias, Section 3',
            'prefix' => 'CHNU',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 20,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Rutheron & Plaza Blanca, Section 7',
            'prefix' => 'CHRU',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 21,
            'adjudication_id' => 4,
            'adjudication_section_name' => 'Chama - Tierra Amarilla, Section 7',
            'prefix' => 'CHTA',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 22,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Carlsbad Irrigation District CID1',
            'prefix' => 'PCON',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 23,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Carlsbad Irrigation District CID2',
            'prefix' => 'PCTW',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 24,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Carlsbad Irrigation District CID3',
            'prefix' => 'PCTH',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 5,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 25,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Carlsbad Irrigation District CID4',
            'prefix' => 'PCFO',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 5,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 26,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Cow Creek',
            'prefix' => 'PRCC',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 6,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 27,
            'adjudication_id' => 7,
            'adjudication_section_name' => 'Jemez',
            'prefix' => 'JMZ',
            'adjudication_section_type_id' => 3,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 28,
            'adjudication_id' => 7,
            'adjudication_section_name' => 'Chama - Rio Puerco',
            'prefix' => 'CHRP',
            'adjudication_section_type_id' => 3,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 29,
            'adjudication_id' => 8,
            'adjudication_section_name' => 'LRG - Northern Mesilla Valley Section',
            'prefix' => 'LRN',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 30,
            'adjudication_id' => 8,
            'adjudication_section_name' => 'LRG - Nutt  Hockett  Section',
            'prefix' => 'NHB',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 31,
            'adjudication_id' => 8,
            'adjudication_section_name' => 'LRG - Outlying Areas  Section',
            'prefix' => 'LRO',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 32,
            'adjudication_id' => 8,
            'adjudication_section_name' => 'LRG - Rincon Valley Section',
            'prefix' => 'LRR',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 33,
            'adjudication_id' => 8,
            'adjudication_section_name' => 'LRG - Southern Mesilla Valley Section',
            'prefix' => 'LRS',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 34,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Gallinas River Section',
            'prefix' => 'GR',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 35,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Pecos Supp.',
            'prefix' => 'PRS',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 36,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Upper Pecos',
            'prefix' => 'PCUP',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 37,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Black River Section',
            'prefix' => 'BLK',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 38,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Fort Sumner',
            'prefix' => 'PCFS',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 39,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Hagerman Canal',
            'prefix' => 'PCHC',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 40,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Rio Bonito',
            'prefix' => 'BON',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 41,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Ruidoso',
            'prefix' => 'RUI',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 42,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - PMD',
            'prefix' => 'PMD',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 43,
            'adjudication_id' => 12,
            'adjudication_section_name' => 'Red River',
            'prefix' => 'RR',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 44,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - River Pumpers',
            'prefix' => 'PCRP',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 45,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Roswell',
            'prefix' => 'RA',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 46,
            'adjudication_id' => 15,
            'adjudication_section_name' => 'San Juan - La Plata',
            'prefix' => 'SJLP',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 3,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 47,
            'adjudication_id' => 15,
            'adjudication_section_name' => 'San Juan NR',
            'prefix' => 'SJNR',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 3,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 48,
            'adjudication_id' => 15,
            'adjudication_section_name' => 'San Juan PR',
            'prefix' => 'SJPR',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 3,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 49,
            'adjudication_id' => 15,
            'adjudication_section_name' => 'San Juan SJ',
            'prefix' => 'SJSJ',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 3,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 50,
            'adjudication_id' => 16,
            'adjudication_section_name' => 'SCT - Santa Cruz',
            'prefix' => 'SCRZ',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 51,
            'adjudication_id' => 16,
            'adjudication_section_name' => 'SCT - Truchas',
            'prefix' => 'TRUC',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 52,
            'adjudication_id' => 17,
            'adjudication_section_name' => 'Santa Fe Vol 1',
            'prefix' => 'SFV1',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 53,
            'adjudication_id' => 17,
            'adjudication_section_name' => 'Santa Fe Vol 2',
            'prefix' => 'SFV2',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 54,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Rio Hondo',
            'prefix' => 'HON',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 55,
            'adjudication_id' => 18,
            'adjudication_section_name' => 'Taos - Grande',
            'prefix' => 'TGR',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 56,
            'adjudication_id' => 18,
            'adjudication_section_name' => 'Taos - Hondo',
            'prefix' => 'THO',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 57,
            'adjudication_id' => 18,
            'adjudication_section_name' => 'Taos - Pueblo',
            'prefix' => 'TPL',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-07-16 12:34:02',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-07-16 12:34:02',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 58,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Intrepid',
            'prefix' => 'INT',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 8,  //TODO: confirm data is correct, excel files say status_id is 9 but there are only 8,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-08-13 10:55:33',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-08-13 10:55:33',
            'updated_by' => 'Rguidi',
        ]);

        AdjudicationSection::factory()->create([
            'id' => 59,
            'adjudication_id' => 3,
            'adjudication_section_name' => 'Pecos - Roswell Artesian Basin',
            'prefix' => 'RAB',
            'adjudication_section_type_id' => 4,
            'boundary_name' => null,
            'adjudication_section_status_id' => 2,
            'water_source_id' => 3,
            'basin_section' => null,
            'extra_sub_file_tab' => null,
            'show_estate' => null,
            'created_at' => '2024-08-13 10:56:27',
            'created_by' => 'Rguidi',
            'updated_at' => '2024-08-13 10:56:27',
            'updated_by' => 'Rguidi',
        ]);
    }
}
