<?php

namespace Database\Seeders;

use App\Models\Subfile;
use Illuminate\Database\Seeder;

class SubfilesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Subfile::factory()->create([
            'adjudication_section_id' => 1,
            'basin_nbr_hl' => null,
            'basin_section_hl' => 'AAM',
            'batch' => null,
            'file_location_id' => null,
            'prev_sub_id' => null,
            'print_file' => null,
            'selected' => false,
            'sub_file_assigned_ose_attorney_person_id' => null,
            'sub_file_end_date' => null,
            'sub_file_group' => null,
            'sub_file_hl_sfx' => null,
            'sub_file_hl_txt' => '10.15',
            'sub_file_map_nbr' => null,
            'sub_file_parent_id' => null,
            'sub_file_sort' => 10.15,
            'sub_file_start_date' => '00:00.0',
            'sub_file_type_nbr' => null,
            'sub_file_var_sort' => null,
            'sub_id_access' => 1258,
            'sub_unk_own' => null,
            'subfile_adjudication_status_id' => 5,
            'verified' => false,
            'wrats_status_date' => null,
            'wrats_status_doc' => 'Hydrographic Survey Published',
            'created_by' => 'Rguidi',
            'updated_by' => 'Rguidi',
        ]);

        Subfile::factory()->create([
            'adjudication_section_id' => 1,
            'basin_nbr_hl' => null,
            'basin_section_hl' => 'AAM',
            'batch' => 0,
            'file_location_id' => null,
            'prev_sub_id' => null,
            'print_file' => null,
            'selected' => false,
            'sub_file_assigned_ose_attorney_person_id' => null,
            'sub_file_end_date' => null,
            'sub_file_group' => null,
            'sub_file_hl_sfx' => null,
            'sub_file_hl_txt' => '10.151',
            'sub_file_map_nbr' => null,
            'sub_file_parent_id' => null,
            'sub_file_sort' => 10.151,
            'sub_file_start_date' => '00:00.0',
            'sub_file_type_nbr' => null,
            'sub_file_var_sort' => null,
            'sub_id_access' => 1259,
            'sub_unk_own' => null,
            'subfile_adjudication_status_id' => 3,
            'verified' => false,
            'wrats_status_date' => null,
            'wrats_status_doc' => 'Hydrographic Survey Published',
            'created_by' => 'Rguidi',
            'updated_by' => 'Rguidi',
        ]);
        Subfile::factory()->create([
            'adjudication_section_id' => 1,
            'basin_nbr_hl' => null,
            'basin_section_hl' => 'AAM',
            'batch' => null,
            'file_location_id' => null,
            'prev_sub_id' => null,
            'print_file' => null,
            'selected' => false,
            'sub_file_assigned_ose_attorney_person_id' => null,
            'sub_file_end_date' => null,
            'sub_file_group' => null,
            'sub_file_hl_sfx' => null,
            'sub_file_hl_txt' => '10.16',
            'sub_file_map_nbr' => null,
            'sub_file_parent_id' => null,
            'sub_file_sort' => 10.016,
            'sub_file_start_date' => '00:00.0',
            'sub_file_type_nbr' => null,
            'sub_file_var_sort' => null,
            'sub_id_access' => 1260,
            'sub_unk_own' => null,
            'subfile_adjudication_status_id' => 3,
            'verified' => false,
            'wrats_status_date' => null,
            'wrats_status_doc' => 'Hydrographic Survey Published',
            'created_by' => 'Rguidi',
            'updated_by' => 'Rguidi',
        ]);

        Subfile::factory()->create([
            'adjudication_section_id' => 1,
            'basin_nbr_hl' => null,
            'basin_section_hl' => 'AAM',
            'batch' => null,
            'file_location_id' => null,
            'prev_sub_id' => null,
            'print_file' => null,
            'selected' => false,
            'sub_file_assigned_ose_attorney_person_id' => null,
            'sub_file_end_date' => null,
            'sub_file_group' => null,
            'sub_file_hl_sfx' => 'A',
            'sub_file_hl_txt' => '10.16A',
            'sub_file_map_nbr' => null,
            'sub_file_parent_id' => null,
            'sub_file_sort' => 10.016,
            'sub_file_start_date' => '00:00.0',
            'sub_file_type_nbr' => null,
            'sub_file_var_sort' => null,
            'sub_id_access' => 1261,
            'sub_unk_own' => null,
            'subfile_adjudication_status_id' => 4,
            'verified' => false,
            'wrats_status_date' => null,
            'wrats_status_doc' => 'Hydrographic Survey Published',
            'created_by' => 'Rguidi',
            'updated_by' => 'Rguidi',
        ]);

        Subfile::factory()->create([
            'adjudication_section_id' => 1,
            'basin_nbr_hl' => null,
            'basin_section_hl' => 'AAM',
            'batch' => null,
            'file_location_id' => null,
            'prev_sub_id' => null,
            'print_file' => null,
            'selected' => false,
            'sub_file_assigned_ose_attorney_person_id' => null,
            'sub_file_end_date' => null,
            'sub_file_group' => null,
            'sub_file_hl_sfx' => 'B',
            'sub_file_hl_txt' => '10.16B',
            'sub_file_map_nbr' => null,
            'sub_file_parent_id' => null,
            'sub_file_sort' => 10.016,
            'sub_file_start_date' => '00:00.0',
            'sub_file_type_nbr' => null,
            'sub_file_var_sort' => null,
            'sub_id_access' => 1262,
            'sub_unk_own' => null,
            'subfile_adjudication_status_id' => 4,
            'verified' => false,
            'wrats_status_date' => '00:00.0',
            'wrats_status_doc' => 'Subfile Order Filed',
            'created_by' => 'Rguidi',
            'updated_by' => 'Rguidi',
        ]);

        Subfile::factory()->create([
            'adjudication_section_id' => 1,
            'basin_nbr_hl' => null,
            'basin_section_hl' => 'AAM',
            'batch' => null,
            'file_location_id' => null,
            'prev_sub_id' => null,
            'print_file' => null,
            'selected' => false,
            'sub_file_assigned_ose_attorney_person_id' => null,
            'sub_file_end_date' => null,
            'sub_file_group' => null,
            'sub_file_hl_sfx' => null,
            'sub_file_hl_txt' => '10.17',
            'sub_file_map_nbr' => null,
            'sub_file_parent_id' => null,
            'sub_file_sort' => 10.017,
            'sub_file_start_date' => '00:00.0',
            'sub_file_type_nbr' => null,
            'sub_file_var_sort' => null,
            'sub_id_access' => 1263,
            'sub_unk_own' => null,
            'subfile_adjudication_status_id' => 5,
            'verified' => false,
            'wrats_status_date' => null,
            'wrats_status_doc' => 'Hydrographic Survey Published',
            'created_by' => 'Rguidi',
            'updated_by' => 'Rguidi',
        ]);

        Subfile::factory()->create([
            'adjudication_section_id' => 1,
            'basin_nbr_hl' => null,
            'basin_section_hl' => 'AAM',
            'batch' => 1,
            'file_location_id' => null,
            'prev_sub_id' => null,
            'print_file' => null,
            'selected' => false,
            'sub_file_assigned_ose_attorney_person_id' => null,
            'sub_file_end_date' => null,
            'sub_file_group' => null,
            'sub_file_hl_sfx' => null,
            'sub_file_hl_txt' => '10.19',
            'sub_file_map_nbr' => null,
            'sub_file_parent_id' => null,
            'sub_file_sort' => 10.019,
            'sub_file_start_date' => '00:00.0',
            'sub_file_type_nbr' => null,
            'sub_file_var_sort' => null,
            'sub_id_access' => 1265,
            'sub_unk_own' => null,
            'subfile_adjudication_status_id' => 5,
            'verified' => false,
            'wrats_status_date' => '00:00.0',
            'wrats_status_doc' => 'Subfile Order Filed',
            'created_by' => 'Rguidi',
            'updated_by' => 'Rguidi',
        ]);

        // Continue similarly for the rest of the records...

        // Repeat this structure for each record in your dataset

    }
}
